const SCHEDULE_HEIGHT = 37;
const SCHEDULE_WIDTH = 320;
const SCHEDULE_MARGIN_TOP = 5;
const SCHEDULE_MARGIN_BOTTOM = 5;
const SCHEDULE_MARGIN_LEFT = 5;

export {
  SCHEDULE_HEIGHT,
  SCHEDULE_WIDTH,
  SCHEDULE_MARGIN_TOP,
  SCHEDULE_MARGIN_BOTTOM,
  SCHEDULE_MARGIN_LEFT,
};
