// HEADER
const HEADER_Z_INDEX = 5;

const PLAN_HEADER_Z_INDEX = 6;

// TRIP PLAN
const GOOGLE_MAP_Z_INDEX = 3;

const PLAN_LEFT_WINDOW_Z_INDEX = 4;

const PLACE_SEARCH_INPUT_Z_INDEX = 1;

const SCHEDULE_TAB_DROPDOWN_Z_INDEX = 1;

// LOADING
const LOADING_Z_INDEX = 10;

export {
  HEADER_Z_INDEX,
  PLAN_HEADER_Z_INDEX,
  GOOGLE_MAP_Z_INDEX,
  PLAN_LEFT_WINDOW_Z_INDEX,
  PLACE_SEARCH_INPUT_Z_INDEX,
  SCHEDULE_TAB_DROPDOWN_Z_INDEX,
  LOADING_Z_INDEX,
};
