// HEADER
const HEADER_Z_INDEX = 5;

const TRIP_HEADER_Z_INDEX = 6;

// TRIP LIST
const TRIP_LIST_DIM_LAYER_Z_INDEX = 1;

const NEW_TRIP_CARD_Z_INDEX = 2;

const OPTION_OPEN_TRIP_CARD_Z_INDEX = 2;

// TRIP
const GOOGLE_MAP_Z_INDEX = 3;

const TRIP_LEFT_WINDOW_Z_INDEX = 4;

const PLACE_SEARCH_INPUT_Z_INDEX = 1;

const SCHEDULE_TAB_DROPDOWN_Z_INDEX = 1;

// LOADING
const LOADING_Z_INDEX = 10;

export {
  HEADER_Z_INDEX,
  TRIP_HEADER_Z_INDEX,
  TRIP_LIST_DIM_LAYER_Z_INDEX,
  NEW_TRIP_CARD_Z_INDEX,
  OPTION_OPEN_TRIP_CARD_Z_INDEX,
  GOOGLE_MAP_Z_INDEX,
  TRIP_LEFT_WINDOW_Z_INDEX,
  PLACE_SEARCH_INPUT_Z_INDEX,
  SCHEDULE_TAB_DROPDOWN_Z_INDEX,
  LOADING_Z_INDEX,
};
