name: Auto Deploy after push

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: auto-deploy
    steps:
      - name: Checkout source code.
        uses: actions/checkout@v3

      - name: 리액트 빌드
        run: |
          npm install
          npm run build
        env:
          API_SERVER: ${{ secrets.API_SERVER }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          KAKAO_CLIENT_ID: ${{ secrets.KAKAO_CLIENT_ID }}
          NAVER_CLIENT_ID: ${{ secrets.NAVER_CLIENT_ID }}
          GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
          OPEN_AI_API_KEY: ${{ secrets.OPEN_AI_API_KEY }}
          OAUTH_REDIRECT_URI: ${{ vars.OAUTH_REDIRECT_URI }}

      - name: 빌드한 파일 S3에 업로드
        run: aws s3 sync dist s3://${{ secrets.AWS_BUCKET_NAME }} --region ${{secrets.AWS_BUCKET_REGION}} --acl public-read --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_IAM_MANAGER_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_IAM_MANAGER_SECRET_ACCESS_KEY }}
